name: build process
run-name: Build process

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}
  schedule:
    - cron: '0 0 1 */2 *'

jobs:

  trigger-build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Start containers build - Fedora-ELN
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-containers.yml',
              ref: context.ref,
            });


  wait-for-build-containers-arm64:
    runs-on: ubuntu-latest
    needs: trigger-build-containers
    steps:
      - name: Wait for build-containers to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'build-container-fedora-arm64 (ubuntu-24.04-arm)'
          wait-interval: 10

  wait-for-build-containers-amd64:
    runs-on: ubuntu-latest
    needs: trigger-build-containers
    steps:
      - name: Wait for build-containers to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'build-container-fedora-amd64 (ubuntu-24.04)'
          wait-interval: 10